# Generated by Django 6.0.1 on 2026-01-30 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('graph', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('simple', 'SIMPLE'), ('exam', 'EXAM')], default='simple', max_length=32)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='graph.subject')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('finished', 'FINISHED'), ('abandoned', 'ABANDONED')], default='started', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='training.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test attempt',
                'verbose_name_plural': 'Test attempts',
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_payload', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('applied_scoring_policy', models.JSONField(blank=True, null=True)),
                ('applied_max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attempts', to=settings.AUTH_USER_MODEL)),
                ('test_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attempts', to='training.testattempt')),
            ],
            options={
                'verbose_name': 'Task attempt',
                'verbose_name_plural': 'Task attempts',
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('max_score', models.PositiveSmallIntegerField(default=1)),
                ('exam_task_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_items', to='exams.examtaskgroup')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_items', to='tasks.task')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.test')),
            ],
            options={
                'verbose_name': 'Test item',
                'verbose_name_plural': 'Test items',
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['subject', 'mode'], name='training_te_subject_64016a_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'status', 'started_at'], name='training_te_user_id_489bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'status', 'started_at'], name='training_te_test_id_d49ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['user', 'task', 'submitted_at'], name='training_ta_user_id_e922f2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['test_attempt', 'submitted_at'], name='training_ta_test_at_a08985_idx'),
        ),
        migrations.AddIndex(
            model_name='testitem',
            index=models.Index(fields=['test', 'order'], name='training_te_test_id_abc47e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testitem',
            unique_together={('test', 'order')},
        ),
    ]
