# Generated by Django 6.0.1 on 2026-01-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskattempt',
            options={'verbose_name': 'Попытка задания', 'verbose_name_plural': 'Попытки заданий'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'verbose_name': 'Попытка теста', 'verbose_name_plural': 'Попытки тестов'},
        ),
        migrations.AlterModelOptions(
            name='testitem',
            options={'verbose_name': 'Элемент теста', 'verbose_name_plural': 'Элементы теста'},
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='exam_task_group',
        ),
    ]
