# Generated by Django 6.0.1 on 2026-01-30 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('concept', 'CONCEPT'), ('skill', 'SKILL'), ('law', 'LAW'), ('case', 'CASE')], default='concept', max_length=32)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='graph.concept')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='graph.subject')),
            ],
            options={
                'verbose_name': 'Graph node',
                'verbose_name_plural': 'Graph nodes',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('prerequisite', 'PREREQUISITE'), ('part_of', 'PART_OF'), ('depends_on', 'DEPENDS_ON')], default='prerequisite', max_length=32)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_in', to='graph.node')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_out', to='graph.node')),
            ],
            options={
                'verbose_name': 'Graph relation',
                'verbose_name_plural': 'Graph relations',
                'indexes': [models.Index(fields=['parent', 'type'], name='graph_relat_parent__696f8e_idx'), models.Index(fields=['child', 'type'], name='graph_relat_child_i_1b7d6c_idx')],
                'unique_together': {('parent', 'child', 'type')},
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['subject', 'type'], name='graph_node_subject_8780b9_idx'),
        ),
    ]
