# Generated by Django 6.0.1 on 2026-01-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'Концепция', 'verbose_name_plural': 'Концепции'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Вершина графа', 'verbose_name_plural': 'Вершины графа'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'Связь графа', 'verbose_name_plural': 'Связи графа'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AddField(
            model_name='concept',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concepts', to='graph.subject'),
        ),
    ]
