# Generated by Django 6.0.1 on 2026-01-30 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='ExamTaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('task_type', models.CharField(max_length=64)),
                ('scoring_policy', models.JSONField(blank=True, default=dict)),
                ('max_score', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Exam task group',
                'verbose_name_plural': 'Exam task groups',
            },
        ),
        migrations.CreateModel(
            name='ExamTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='exams.examtaskgroup')),
            ],
            options={
                'verbose_name': 'Exam task type',
                'verbose_name_plural': 'Exam task types',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=32, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_types', to='graph.subject')),
            ],
            options={
                'verbose_name': 'Exam type',
                'verbose_name_plural': 'Exam types',
            },
        ),
        migrations.AddField(
            model_name='examtaskgroup',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_groups', to='exams.examtype'),
        ),
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['exam', 'subject', 'is_active'], name='exams_examt_exam_id_fb2bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='examtaskgroup',
            index=models.Index(fields=['exam_type', 'num'], name='exams_examt_exam_ty_a5df61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examtaskgroup',
            unique_together={('exam_type', 'num')},
        ),
    ]
