# Generated by Django 6.0.1 on 2026-01-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='examtaskgroup',
            options={'verbose_name': 'Группа (номер) экзаменационного задания', 'verbose_name_plural': 'Группы (номера) экзаменационных заданий'},
        ),
        migrations.AlterModelOptions(
            name='examtasktype',
            options={'verbose_name': 'Тип задания (внутри группы)', 'verbose_name_plural': 'Типы заданий (внутри группы)'},
        ),
        migrations.AlterModelOptions(
            name='examtype',
            options={'verbose_name': 'Экзамен по предмету', 'verbose_name_plural': 'Экзамены по предметам'},
        ),
        migrations.RemoveField(
            model_name='examtaskgroup',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='examtype',
            name='level',
        ),
        migrations.RemoveField(
            model_name='examtype',
            name='year',
        ),
    ]
