# Generated by Django 6.0.1 on 2026-01-30 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('single_choice', 'SINGLE_CHOICE'), ('multi_choice', 'MULTI_CHOICE'), ('number', 'NUMBER'), ('short_text', 'SHORT_TEXT'), ('match', 'MATCH')], max_length=64)),
                ('prompt', models.TextField()),
                ('solution_text', models.TextField(blank=True, default='')),
                ('type_payload', models.JSONField(blank=True, default=dict)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='exams.examtasktype')),
                ('nodes', models.ManyToManyField(blank=True, related_name='tasks', to='graph.node')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='graph.subject')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'indexes': [models.Index(fields=['subject', 'task_type'], name='tasks_task_subject_66d1e8_idx')],
            },
        ),
    ]
