# Generated by Django 6.0.1 on 2026-01-30 13:10

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_task_nodes(apps, schema_editor):
    """
    We previously used an implicit M2M table for Task.nodes (tasks_task_nodes).
    After introducing an explicit through model (TaskNode), copy existing links.
    """

    connection = schema_editor.connection
    old_table = "tasks_task_nodes"

    if old_table not in connection.introspection.table_names():
        return

    TaskNode = apps.get_model("tasks", "TaskNode")

    with connection.cursor() as cursor:
        cursor.execute(f"SELECT task_id, node_id FROM {old_table}")
        rows = cursor.fetchall()

    if not rows:
        return

    TaskNode.objects.bulk_create(
        [TaskNode(task_id=task_id, node_id=node_id) for task_id, node_id in rows],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_tasks', to='graph.node')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_nodes', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task-node link',
                'verbose_name_plural': 'Task-node links',
            },
        ),
        migrations.RunPython(forwards_copy_task_nodes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='task',
            name='nodes',
        ),
        migrations.AddField(
            model_name='task',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='tasks.TaskNode', to='graph.node'),
        ),
        migrations.AddIndex(
            model_name='tasknode',
            index=models.Index(fields=['task', 'node'], name='tasks_taskn_task_id_9a189e_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknode',
            index=models.Index(fields=['node', 'task'], name='tasks_taskn_node_id_609c86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasknode',
            unique_together={('task', 'node')},
        ),
        migrations.RunSQL("DROP TABLE IF EXISTS tasks_task_nodes;", migrations.RunSQL.noop),
    ]
